run: 
	#g++ -std=c++11 -o main main.cpp
	g++ -std=c++11 *.cpp -o main
	./main

run-client: 
	g++ -std=c++11 simple-client.cpp -o client
	./client

run-server:
	g++ -std=c++11 simple-server.cpp -o simple-server
	./simple-server

clean:
	rm *.o output
